# Build script used by gitlab.medelexis.ch
stages:
    - build
    - deploy

build:
  script: "mvn clean verify -Dmaven.test.skip=true"
  artifacts:
    paths:
    - ch.elexis.base.p2site/target/*.zip
    expire_in: 1 day

deploy_master_snapshot:
    stage: deploy
    script:
    - wget https://raw.githubusercontent.com/elexis/elexis-3-core/master/ch.elexis.core.releng/upload-dav.sh; chmod +x upload-dav.sh
    - mkdir upload; unzip ch.elexis.base.p2site/target/ch.elexis.base.p2site*.zip -d upload/
    - ./upload-dav.sh upload/ https://download.elexis.info/elexis/p2/ $CI_COMMIT_REF_NAME/elexis-3-base $DEPLOY_USER $DEPLOY_PASSWORD
    - rm -Rf upload/
    - rm upload-dav.sh
    environment:
        name: elexis-3-base/$CI_COMMIT_REF_NAME
        url: http://download.elexis.info/elexis/p2/$CI_COMMIT_REF_NAME/elexis-3-base
    only:
    - master
