---
language: java

install: mvn --batch-mode -V --quiet -DskipTests=true -Dmaven.javadoc.skip=true validate -Dgit.target.branch=$TRAVIS_BRANCH -Dgit.core.branch=$TRAVIS_BRANCH

script: mvn --batch-mode -V clean verify --fail-at-end -Dgit.target.branch=$TRAVIS_BRANCH -Dgit.core.branch=$TRAVIS_BRANCH
  
notifications:
  email:
  - niklaus.giger@member.fsf.org
jdk:
  - openjdk8

services:
  - xvfb

cache:
  directories:
  - $HOME/.m2
