---
language: java

matrix:
  include:
  - name: "Deutsch"
    env: NL=de_CH
  - name: "English"
    env:  NL=en_US
  - name: "Français"
    env: NL=fr_CH
  allow_failures:
  - name: "English"
  - name: "Français"
  
install: mvn --batch-mode -V -Dgit.target.branch=$TRAVIS_BRANCH -Dgit.core.branch=$TRAVIS_BRANCH -DskipTests=true -Dmaven.javadoc.skip=true clean validate --quiet

script: mvn  --batch-mode -V -Dgit.target.branch=$TRAVIS_BRANCH -Dgit.core.branch=$TRAVIS_BRANCH -DNL=$NL --fail-at-end clean verify
  
notifications:
  email:
  - niklaus.giger@member.fsf.org
jdk:
  - openjdk8

services:
  - xvfb

cache:
  directories:
  - $HOME/.m2
